#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# android.sh — Android colour-resources export for palGen
# ═══════════════════════════════════════════════════════════════════════════════
# Emits res/values/colors.xml with <color name="primary_500">#RRGGBB</color>.
# Hyphens in token names become underscores (Android resource-name rules).
# ═══════════════════════════════════════════════════════════════════════════════

generate_android() {
    local outfile="${OUTPUT_DIR}/$(safe_theme_name).colors.xml"

    local body="" i aname ahex
    for i in "${!TOKEN_NAMES[@]}"; do
        aname="${TOKEN_NAMES[$i]//-/_}"
        ahex="${TOKEN_HEXES[$i]#\#}"
        body+="    <color name=\"${aname}\">#${ahex^^}</color>"$'\n'
    done
    body="${body%$'\n'}"

    local content
    content="$(cat << XMLEOF
<?xml version="1.0" encoding="utf-8"?>
<!-- ${THEME_NAME} — Android colour resources -->
<!-- Generated by palGen (https://github.com/XAOSTECH/design-flows) -->
<resources>
${body}
</resources>
XMLEOF
)"

    write_target_file "$outfile" "$content"
}
