#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# css.sh — CSS custom-properties export for palGen
# ═══════════════════════════════════════════════════════════════════════════════
# Emits every token as a :root custom property (--primary-500: #...;).
# ═══════════════════════════════════════════════════════════════════════════════

generate_css() {
    local outfile="${OUTPUT_DIR}/$(safe_theme_name).css"

    local body="" i
    for i in "${!TOKEN_NAMES[@]}"; do
        body+="  --${TOKEN_NAMES[$i]}: ${TOKEN_HEXES[$i]};"$'\n'
    done
    body="${body%$'\n'}"

    local content
    content="$(cat << CSSEOF
/* ═══════════════════════════════════════════════════════════════════
 * ${THEME_NAME} — CSS custom properties
 * Generated by palGen (https://github.com/XAOSTECH/design-flows)
 * Colours derived with pastel (https://github.com/sharkdp/pastel)
 * ═══════════════════════════════════════════════════════════════════ */

:root {
${body}
}
CSSEOF
)"

    write_target_file "$outfile" "$content"
}
