#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# gpl.sh — GIMP / Inkscape palette export for palGen
# ═══════════════════════════════════════════════════════════════════════════════
# Emits a .gpl palette file usable by GIMP, Inkscape, Krita and friends.
# Each entry is "R G B<TAB>token-name".
# ═══════════════════════════════════════════════════════════════════════════════

generate_gpl() {
    local outfile="${OUTPUT_DIR}/$(safe_theme_name).gpl"

    local body="" i rgb
    for i in "${!TOKEN_NAMES[@]}"; do
        rgb=$(hex_rgb_spaced "${TOKEN_HEXES[$i]}")
        body+="${rgb}"$'\t'"${TOKEN_NAMES[$i]}"$'\n'
    done
    body="${body%$'\n'}"

    local content
    content="$(cat << GPLEOF
GIMP Palette
Name: ${THEME_NAME}
Columns: 10
# Generated by palGen (https://github.com/XAOSTECH/design-flows)
# Colours derived with pastel (https://github.com/sharkdp/pastel)
#
${body}
GPLEOF
)"

    write_target_file "$outfile" "$content"
}
