#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# json.sh — W3C design-tokens export for palGen
# ═══════════════════════════════════════════════════════════════════════════════
# Emits nested design tokens following the W3C Design Tokens format
# (groups of { "$value": "#...", "$type": "color" }).
# ═══════════════════════════════════════════════════════════════════════════════

generate_json() {
    local outfile="${OUTPUT_DIR}/$(safe_theme_name).tokens.json"

    local groups_json="" g
    for g in "${TOKEN_GROUPS[@]}"; do
        local entries="" key hex
        while IFS=$'\t' read -r key hex; do
            entries+="      \"${key}\": { \"\$value\": \"${hex}\", \"\$type\": \"color\" },"$'\n'
        done < <(tokens_in_group "$g")
        entries="${entries%,$'\n'}"
        groups_json+="    \"${g}\": {"$'\n'"${entries}"$'\n'"    },"$'\n'
    done
    groups_json="${groups_json%,$'\n'}"

    local content
    content="$(cat << JSONEOF
{
  "\$description": "${THEME_NAME} palette — generated by palGen",
  "\$type": "color",
${groups_json}
}
JSONEOF
)"

    write_target_file "$outfile" "$content"
}
