#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# scss.sh — SCSS variables & Sass map export for palGen
# ═══════════════════════════════════════════════════════════════════════════════
# Emits flat SCSS variables ($primary-500: #...;) plus a $palette Sass map.
# ═══════════════════════════════════════════════════════════════════════════════

generate_scss() {
    local outfile="${OUTPUT_DIR}/_$(safe_theme_name).scss"

    local vars="" map="" i
    for i in "${!TOKEN_NAMES[@]}"; do
        vars+="\$${TOKEN_NAMES[$i]}: ${TOKEN_HEXES[$i]};"$'\n'
        map+="  \"${TOKEN_NAMES[$i]}\": ${TOKEN_HEXES[$i]},"$'\n'
    done
    vars="${vars%$'\n'}"
    map="${map%,$'\n'}"

    local content
    content="$(cat << SCSSEOF
// ═══════════════════════════════════════════════════════════════════
// ${THEME_NAME} — SCSS variables & palette map
// Generated by palGen (https://github.com/XAOSTECH/design-flows)
// Colours derived with pastel (https://github.com/sharkdp/pastel)
// ═══════════════════════════════════════════════════════════════════

${vars}

\$palette: (
${map}
);
SCSSEOF
)"

    write_target_file "$outfile" "$content"
}
