#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# tailwind.sh — Tailwind CSS colour-config export for palGen
# ═══════════════════════════════════════════════════════════════════════════════
# Emits a CommonJS module grouping tokens into nested colour scales, ready for
#   theme: { extend: { colors: require('./<name>.tailwind.js') } }
# ═══════════════════════════════════════════════════════════════════════════════

generate_tailwind() {
    local name
    name=$(safe_theme_name)
    local outfile="${OUTPUT_DIR}/${name}.tailwind.js"

    local groups_js="" g
    for g in "${TOKEN_GROUPS[@]}"; do
        local entries="" key hex
        while IFS=$'\t' read -r key hex; do
            entries+="      '${key}': '${hex}',"$'\n'
        done < <(tokens_in_group "$g")
        entries="${entries%$'\n'}"
        groups_js+="    '${g}': {"$'\n'"${entries}"$'\n'"    },"$'\n'
    done
    groups_js="${groups_js%,$'\n'}"

    local content
    content="$(cat << TWEOF
// ═══════════════════════════════════════════════════════════════════
// ${THEME_NAME} — Tailwind CSS colour tokens
// Generated by palGen (https://github.com/XAOSTECH/design-flows)
// Usage: theme: { extend: { colors: require('./${name}.tailwind.js') } }
// ═══════════════════════════════════════════════════════════════════

module.exports = {
${groups_js}
};
TWEOF
)"

    write_target_file "$outfile" "$content"
}
