#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# chrome.sh — Chrome/Chromium browser theme target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates a Chrome theme extension directory with manifest.json.
# The theme can be loaded via chrome://extensions in developer mode.
# ═══════════════════════════════════════════════════════════════════════════════

_hex_to_rgb_array() {
    local hex="${1#\#}"
    printf "%d, %d, %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

generate_chrome() {
    local outdir="${OUTPUT_DIR}/${THEME_NAME}/chrome"
    local outfile="${outdir}/manifest.json"

    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg_colour accent_colour bg_colour
    fg_colour="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    accent_colour="${PRIMARY_SHADES[5]:-$primary_hex}"
    bg_colour="$(set_lightness "$tertiary_hex" "$BG_LIGHTNESS")"

    local toolbar_colour tab_bg_colour
    toolbar_colour="$(lighten "$bg_colour" 0.05)"
    tab_bg_colour="$(lighten "$bg_colour" 0.08)"

    local frame_rgb tab_text_rgb tab_bg_rgb toolbar_rgb
    frame_rgb=$(_hex_to_rgb_array "$bg_colour")
    tab_text_rgb=$(_hex_to_rgb_array "$fg_colour")
    tab_bg_rgb=$(_hex_to_rgb_array "$tab_bg_colour")
    toolbar_rgb=$(_hex_to_rgb_array "$toolbar_colour")

    local accent_rgb bg_rgb fg_rgb
    accent_rgb=$(_hex_to_rgb_array "$accent_colour")
    bg_rgb=$(_hex_to_rgb_array "$bg_colour")
    fg_rgb=$(_hex_to_rgb_array "$fg_colour")

    local button_bg_rgb
    button_bg_rgb=$(_hex_to_rgb_array "$(lighten "$bg_colour" 0.1)")

    local safe_name
    safe_name=$(echo "$THEME_NAME" | tr ' ' '-' | tr -cd '[:alnum:]-_')

    local json
    json="$(cat << JSONEOF
{
  "manifest_version": 3,
  "version": "1.0.0",
  "name": "${THEME_NAME}",
  "description": "Generated by uiGen (https://github.com/XAOSTECH/design-flows) — colours derived with pastel (https://github.com/sharkdp/pastel)",
  "theme": {
    "colours": {
      "frame":                        [${frame_rgb}],
      "frame_inactive":               [${bg_rgb}],
      "frame_incognito":              [${bg_rgb}],
      "frame_incognito_inactive":     [${bg_rgb}],
      "toolbar":                      [${toolbar_rgb}],
      "tab_text":                     [${tab_text_rgb}],
      "tab_background_text":          [${fg_rgb}],
      "tab_background_text_inactive": [${fg_rgb}],
      "bookmark_text":                [${tab_text_rgb}],
      "ntp_background":               [${bg_rgb}],
      "ntp_text":                     [${fg_rgb}],
      "ntp_link":                     [${accent_rgb}],
      "button_background":            [${button_bg_rgb}]
    },
    "tints": {
      "buttons":          [0.0, 0.0, 0.7],
      "frame_inactive":   [0.0, 0.0, 0.5],
      "background_tab":   [0.0, 0.0, 0.6]
    },
    "properties": {
      "ntp_background_alignment": "bottom"
    }
  }
}
JSONEOF
)"

    write_target_file "$outfile" "$json"
}
