#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# firefox.sh — Firefox browser theme target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates a Firefox theme extension directory with manifest.json.
# Can be loaded as a temporary add-on via about:debugging.
# ═══════════════════════════════════════════════════════════════════════════════

generate_firefox() {
    local outfile="${OUTPUT_DIR}/${THEME_NAME}/firefox/manifest.json"

    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg accent bg toolbar
    fg="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    accent="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"
    bg="$(set_lightness "$tertiary_hex" "$BG_LIGHTNESS")"
    toolbar="$(lighten "$bg" 0.05)"

    local tab_selected popup_bg popup_text
    tab_selected="$(lighten "$bg" 0.1)"
    popup_bg="$(lighten "$bg" 0.03)"
    popup_text="$fg"

    local safe_name
    safe_name=$(echo "$THEME_NAME" | tr ' ' '-' | tr -cd '[:alnum:]-_' | tr '[:upper:]' '[:lower:]')

    local json
    json="$(cat << JSONEOF
{
  "manifest_version": 2,
  "version": "1.0.0",
  "name": "${THEME_NAME}",
  "description": "Generated by uiGen (https://github.com/XAOSTECH/design-flows) — colours derived with pastel (https://github.com/sharkdp/pastel)",
  "browser_specific_settings": {
    "gecko": {
      "id": "${safe_name}@uigen.xaostech"
    }
  },
  "theme": {
    "colors": {
      "frame": "${bg}",
      "frame_inactive": "${bg}",
      "tab_background_text": "${fg}",
      "tab_selected": "${tab_selected}",
      "tab_text": "${fg}",
      "tab_line": "${accent}",
      "tab_loading": "${accent}",
      "toolbar": "${toolbar}",
      "toolbar_text": "${fg}",
      "toolbar_field": "${popup_bg}",
      "toolbar_field_text": "${popup_text}",
      "toolbar_field_border": "${accent}",
      "toolbar_field_focus": "${tab_selected}",
      "toolbar_top_separator": "transparent",
      "toolbar_bottom_separator": "${accent}",
      "popup": "${popup_bg}",
      "popup_text": "${popup_text}",
      "popup_border": "${accent}",
      "popup_highlight": "${tab_selected}",
      "popup_highlight_text": "${fg}",
      "sidebar": "${bg}",
      "sidebar_text": "${fg}",
      "sidebar_highlight": "${tab_selected}",
      "sidebar_highlight_text": "${fg}",
      "ntp_background": "${bg}",
      "ntp_text": "${fg}",
      "icons_attention": "${accent}"
    }
  }
}
JSONEOF
)"

    write_target_file "$outfile" "$json"
}
