#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# gdm.sh — GDM login screen theme target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates a gnome-shell.css variant tailored for the GDM login screen.
# Uses the same GNOME Shell CSS selectors but focused on login-specific
# elements (login-dialog, user list, auth prompts).
#
# Installation requires compiling into a .gresource:
#   glib-compile-resources gnome-shell-theme.gresource.xml
# ═══════════════════════════════════════════════════════════════════════════════

generate_gdm() {
    local outdir="${OUTPUT_DIR}/${THEME_NAME}/gdm"
    local css_file="${outdir}/gnome-shell.css"
    local gresource_file="${outdir}/gnome-shell-theme.gresource.xml"

    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg_colour accent_colour accent_bright
    fg_colour="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    accent_colour="${PRIMARY_SHADES[5]:-$primary_hex}"
    accent_bright="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"

    local bg_deep bg_mid
    bg_deep="$tertiary_hex"
    bg_mid="$secondary_hex"

    local border_colour glow_colour
    border_colour="${PRIMARY_SHADES[6]:-$(lighten "$primary_hex" 0.25)}"
    glow_colour="${BLEND_COLOURS[0]:-$(mix_colors "$primary_hex" "$secondary_hex" 0.5)}"

    local bg_deep_rgb bg_mid_rgb accent_bright_rgb fg_rgb border_rgb glow_rgb
    bg_deep_rgb=$(hex_to_rgb "$bg_deep")
    bg_mid_rgb=$(hex_to_rgb "$bg_mid")
    accent_bright_rgb=$(hex_to_rgb "$accent_bright")
    fg_rgb=$(hex_to_rgb "$fg_colour")
    border_rgb=$(hex_to_rgb "$border_colour")
    glow_rgb=$(hex_to_rgb "$glow_colour")

    local blur="${BLUR_RADIUS}"
    local radius="${BORDER_RADIUS}"

    local css
    css="$(cat << CSSEOF
/* ═══════════════════════════════════════════════════════════════════
 * ${THEME_NAME} — GDM Login Screen Theme
 * Generated by uiGen (https://github.com/XAOSTECH/design-flows)
 * Colours derived with pastel (https://github.com/sharkdp/pastel)
 * ═══════════════════════════════════════════════════════════════════ */

stage {
  font-family: 'Cantarell', 'Inter', 'Noto Sans', sans-serif;
  color: ${fg_colour};
  background: linear-gradient(45deg,
    rgba(${bg_deep_rgb}, 0.6),
    rgba(${accent_bright_rgb}, 0.2),
    rgba(${bg_mid_rgb}, 0.65),
    rgba(${bg_deep_rgb}, 0.55));
}

/* Login dialog */
.login-dialog {
  background: rgba(${bg_mid_rgb}, 0.4);
  border: 2px solid rgba(${border_rgb}, 0.6);
  border-radius: ${radius}px;
  backdrop-filter: blur(${blur}px);
  box-shadow: 0 0 20px rgba(${glow_rgb}, 0.5),
              0 0 40px rgba(${glow_rgb}, 0.25);
}

.login-dialog-prompt-layout {
  padding: 24px;
}

.login-dialog-prompt-entry {
  background: rgba(${bg_deep_rgb}, 0.6);
  border: 2px solid rgba(${border_rgb}, 0.5);
  border-radius: 8px;
  color: ${fg_colour};
  padding: 10px 16px;
  font-size: 14pt;
}

.login-dialog-prompt-entry:focus {
  border-color: rgba(${border_rgb}, 0.9);
  box-shadow: 0 0 10px rgba(${glow_rgb}, 0.4);
}

.login-dialog-user-list {
  background: transparent;
}

.login-dialog-user-list-item {
  border-radius: 10px;
  padding: 8px 12px;
  transition: all 0.15s ease;
}

.login-dialog-user-list-item:hover,
.login-dialog-user-list-item:focus {
  background: rgba(${glow_rgb}, 0.25);
}

.login-dialog-user-list-item:selected {
  background: rgba(${accent_bright_rgb}, 0.3);
  border: 1px solid rgba(${border_rgb}, 0.6);
}

.login-dialog-banner {
  color: rgba(${fg_rgb}, 0.7);
  font-size: 10pt;
}

.login-dialog-button-box .button {
  background: linear-gradient(135deg, rgba(${bg_mid_rgb}, 0.4), rgba(${bg_deep_rgb}, 0.45));
  border: 1px solid rgba(${border_rgb}, 0.5);
  border-radius: 10px;
  color: ${fg_colour};
}

.login-dialog-button-box .button:hover {
  background: rgba(${glow_rgb}, 0.4);
  border-color: rgba(${border_rgb}, 0.8);
}

/* Lock screen (reused from main shell) */
.screen-shield-background {
  background: linear-gradient(45deg,
    rgba(${bg_deep_rgb}, 0.6),
    rgba(${accent_bright_rgb}, 0.2),
    rgba(${bg_mid_rgb}, 0.65));
}

.unlock-dialog {
  background: rgba(${bg_mid_rgb}, 0.4);
  border: 2px solid rgba(${border_rgb}, 0.6);
  border-radius: ${radius}px;
  backdrop-filter: blur(15px);
  box-shadow: 0 0 20px rgba(${glow_rgb}, 0.5);
}

/* Panel (minimal on login) */
#panel {
  background: rgba(${bg_deep_rgb}, 0.3);
  border-bottom: 1px solid rgba(${border_rgb}, 0.3);
}
CSSEOF
)"

    local gresource_xml
    gresource_xml="$(cat << XMLEOF
<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/org/gnome/shell/theme">
    <file>gnome-shell.css</file>
  </gresource>
</gresources>
XMLEOF
)"

    write_target_file "$css_file" "$css"
    write_target_file "$gresource_file" "$gresource_xml"
}
