#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# grub.sh — GRUB bootloader theme scaffold target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates a theme.txt file with palette-derived menu colours and a minimal
# directory scaffold. The user must supply their own background image.
# ═══════════════════════════════════════════════════════════════════════════════

generate_grub() {
    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg bg accent bg_highlight border
    fg="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    bg="$(set_lightness "$tertiary_hex" "$BG_LIGHTNESS")"
    accent="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"
    bg_highlight="$(lighten "$bg" 0.12)"
    border="${PRIMARY_SHADES[6]:-$(lighten "$primary_hex" 0.25)}"

    # Strip '#' for GRUB colour format
    local fg_g bg_g accent_g bgh_g border_g
    fg_g="${fg#\#}"
    bg_g="${bg#\#}"
    accent_g="${accent#\#}"
    bgh_g="${bg_highlight#\#}"
    border_g="${border#\#}"

    local theme_txt
    theme_txt="$(cat << GRUBEOF
# ═══════════════════════════════════════════════════════════════════
# ${THEME_NAME} — GRUB Bootloader Theme
# Generated by uiGen (https://github.com/XAOSTECH/design-flows)
# Colours derived with pastel (https://github.com/sharkdp/pastel)
#
# Install:
#   1. Copy this directory to /boot/grub/themes/${THEME_NAME}/
#   2. Add to /etc/default/grub:
#        GRUB_THEME="/boot/grub/themes/${THEME_NAME}/theme.txt"
#   3. Run: sudo update-grub
# ═══════════════════════════════════════════════════════════════════

# ─── Global ───────────────────────────────────────────────────────
title-text:     ""
title-font:     "Inter Regular 16"
title-color:    "#${fg_g}"
desktop-color:  "#${bg_g}"
desktop-image:  "background.png"
message-font:   "Inter Regular 12"
message-color:  "#${fg_g}"
message-bg-color: "#${bg_g}"
terminal-font:  "Inter Regular 12"

# ─── Boot Menu ────────────────────────────────────────────────────
+ boot_menu {
    left   = 25%
    top    = 30%
    width  = 50%
    height = 50%

    item_font           = "Inter Regular 14"
    item_color          = "#${fg_g}"
    item_height         = 36
    item_padding        = 8
    item_spacing        = 4

    selected_item_font  = "Inter Bold 14"
    selected_item_color = "#${accent_g}"
    selected_item_pixmap_style = "select_*.png"

    menu_pixmap_style   = "menu_*.png"

    scrollbar           = true
    scrollbar_width     = 4
    scrollbar_thumb     = "scrollbar_thumb.png"
}

# ─── Countdown Label ─────────────────────────────────────────────
+ label {
    left   = 25%
    top    = 82%
    width  = 50%
    align  = "center"
    id     = "__timeout__"
    text   = "Booting in %d seconds"
    font   = "Inter Regular 11"
    color  = "#${fg_g}"
}

# ─── Progress Bar ────────────────────────────────────────────────
+ progress_bar {
    id     = "__timeout__"
    left   = 30%
    top    = 86%
    width  = 40%
    height = 8

    fg_color       = "#${accent_g}"
    bg_color       = "#${bg_g}"
    border_color   = "#${border_g}"

    highlight_style = "highlight_*.png"
    highlight_overlay = true
}
GRUBEOF
)"

    local base="${OUTPUT_DIR}/${THEME_NAME}/grub"
    write_target_file "${base}/theme.txt" "$theme_txt"

    # Scaffold README for asset requirements
    local readme
    readme="$(cat << READMEEOF
# ${THEME_NAME} — GRUB Theme

Colours generated by [uiGen](https://github.com/XAOSTECH/design-flows), derived with [pastel](https://github.com/sharkdp/pastel).

## Required assets

Place the following image assets alongside \`theme.txt\`:

| File                   | Purpose                        |
|------------------------|--------------------------------|
| \`background.png\`      | Desktop background (1920×1080) |
| \`select_c.png\`        | Selected-item centre slice     |
| \`menu_c.png\`          | Menu centre slice              |
| \`scrollbar_thumb.png\` | Scrollbar thumb                |

Optional: \`select_w.png\`, \`select_e.png\` for full 3-slice selected-item.

## Installation

\`\`\`bash
sudo cp -r . /boot/grub/themes/${THEME_NAME}
echo 'GRUB_THEME="/boot/grub/themes/${THEME_NAME}/theme.txt"' | sudo tee -a /etc/default/grub
sudo update-grub
\`\`\`
READMEEOF
)"

    write_target_file "${base}/README.md" "$readme"
}
