#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# gtk.sh — GTK 3/4 theme target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates a single gtk.css that works for both GTK3 and GTK4 via symlink
# (gtk-3.0/ → gtk-4.0/). Covers comprehensive widget theming including
# Libadwaita components.
#
# Agnostic approach: selectors are written to be valid in both GTK3 and GTK4.
# The file-ops.sh create_gtk_dirs() function handles the symlink.
# ═══════════════════════════════════════════════════════════════════════════════

generate_gtk() {
    local base
    base=$(create_gtk_dirs)
    local outfile="${base}/gtk-4.0/gtk.css"

    # ── Derive colours from palette ──────────────────────────────────────────
    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg_colour accent_colour accent_bright
    fg_colour="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    accent_colour="${PRIMARY_SHADES[5]:-$primary_hex}"
    accent_bright="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"

    local bg_window bg_surface bg_deep
    bg_window="$(set_lightness "$tertiary_hex" "$BG_LIGHTNESS")"
    bg_surface="$(lighten "$bg_window" 0.03)"
    bg_deep="$(darken "$bg_window" 0.03)"

    local border_colour glow_colour
    border_colour="${PRIMARY_SHADES[6]:-$(lighten "$primary_hex" 0.25)}"
    glow_colour="${BLEND_COLOURS[0]:-$(mix_colors "$primary_hex" "$secondary_hex" 0.5)}"

    # RGB components
    local bg_window_rgb bg_surface_rgb bg_deep_rgb
    bg_window_rgb=$(hex_to_rgb "$bg_window")
    bg_surface_rgb=$(hex_to_rgb "$bg_surface")
    bg_deep_rgb=$(hex_to_rgb "$bg_deep")

    local accent_rgb accent_bright_rgb fg_rgb border_rgb glow_rgb secondary_rgb
    accent_rgb=$(hex_to_rgb "$accent_colour")
    accent_bright_rgb=$(hex_to_rgb "$accent_bright")
    fg_rgb=$(hex_to_rgb "$fg_colour")
    border_rgb=$(hex_to_rgb "$border_colour")
    glow_rgb=$(hex_to_rgb "$glow_colour")
    secondary_rgb=$(hex_to_rgb "$secondary_hex")

    local radius="${BORDER_RADIUS}"

    # ── Semantic colour variables ────────────────────────────────────────────
    local error_colour warning_colour success_colour info_colour
    error_colour="${COMPLEMENTARY_COLOURS[0]:-$(rotate_hue "$primary_hex" 180)}"
    warning_colour="${ANALOGOUS_COLOURS[2]:-$(rotate_hue "$secondary_hex" 30)}"
    success_colour="${TRIADIC_COLOURS[2]:-$(rotate_hue "$primary_hex" 120)}"
    info_colour="${ANALOGOUS_COLOURS[0]:-$(rotate_hue "$primary_hex" 30)}"
    local error_rgb warning_rgb success_rgb info_rgb
    error_rgb=$(hex_to_rgb "$error_colour")
    warning_rgb=$(hex_to_rgb "$warning_colour")
    success_rgb=$(hex_to_rgb "$success_colour")
    info_rgb=$(hex_to_rgb "$info_colour")

    local destructive_colour suggested_colour
    destructive_colour="$error_colour"
    suggested_colour="$accent_bright"
    local destructive_rgb suggested_rgb
    destructive_rgb=$(hex_to_rgb "$destructive_colour")
    suggested_rgb=$(hex_to_rgb "$suggested_colour")

    # ── Build the CSS ────────────────────────────────────────────────────────
    local css
    css="$(cat << CSSEOF
/* ═══════════════════════════════════════════════════════════════════
 * ${THEME_NAME} — GTK 3/4 Theme (agnostic)
 * Generated by uiGen (https://github.com/XAOSTECH/design-flows)
 * Colours derived with pastel (https://github.com/sharkdp/pastel)
 *
 * This file is valid for both GTK3 and GTK4. The gtk-3.0/ directory
 * is a symlink to gtk-4.0/ for idempotent application.
 * ═══════════════════════════════════════════════════════════════════ */

/* ─── Window & Background ─────────────────────────────────────────── */
window,
window.background,
.background {
  background-color: rgba(${bg_window_rgb}, 0.92);
  color: ${fg_colour};
}

window.csd {
  border-radius: ${radius}px;
}

window.csd decoration {
  border-radius: ${radius}px;
  box-shadow: 0 3px 12px rgba(0, 0, 0, 0.4);
}

.content {
  background-color: rgba(${bg_surface_rgb}, 0.85);
}

.view {
  background-color: rgba(${bg_deep_rgb}, 0.7);
  color: ${fg_colour};
}

/* ─── Headerbar & Titlebar ────────────────────────────────────────── */
headerbar,
.titlebar {
  background: linear-gradient(180deg, rgba(${bg_surface_rgb}, 0.9), rgba(${bg_window_rgb}, 0.85));
  border-bottom: 1px solid rgba(${border_rgb}, 0.3);
  color: ${fg_colour};
  padding: 4px 8px;
  min-height: 36px;
}

headerbar .title,
headerbar .subtitle {
  color: ${fg_colour};
  font-weight: 600;
}

headerbar .subtitle {
  font-size: smaller;
  opacity: 0.8;
}

headerbar button {
  background: transparent;
  border: 1px solid transparent;
  border-radius: 6px;
  color: ${fg_colour};
  transition: all 0.15s ease;
}

headerbar button:hover {
  background: rgba(${accent_rgb}, 0.2);
  border-color: rgba(${border_rgb}, 0.4);
}

headerbar button:active {
  background: rgba(${accent_rgb}, 0.35);
}

windowcontrols button {
  border-radius: 50%;
  min-width: 16px;
  min-height: 16px;
  padding: 2px;
}

/* ─── Buttons ─────────────────────────────────────────────────────── */
button {
  background-color: rgba(${accent_rgb}, 0.25);
  color: ${fg_colour};
  border: 1px solid rgba(${border_rgb}, 0.4);
  border-radius: 8px;
  padding: 8px 16px;
  transition: all 0.15s ease;
}

button:hover {
  background-color: rgba(${glow_rgb}, 0.35);
  border-color: rgba(${border_rgb}, 0.7);
  box-shadow: inset 0 0 8px rgba(${glow_rgb}, 0.2);
}

button:active,
button:pressed {
  background-color: rgba(${bg_deep_rgb}, 0.5);
  border-color: rgba(${border_rgb}, 0.9);
  box-shadow: inset 0 0 12px rgba(${fg_rgb}, 0.3);
}

button.flat {
  background: transparent;
  border-color: transparent;
}

button.flat:hover {
  background: rgba(${accent_rgb}, 0.15);
}

button.suggested-action {
  background-color: rgba(${suggested_rgb}, 0.5);
  color: ${fg_colour};
  border-color: rgba(${suggested_rgb}, 0.7);
  font-weight: 600;
}

button.suggested-action:hover {
  background-color: rgba(${suggested_rgb}, 0.65);
  box-shadow: 0 0 8px rgba(${suggested_rgb}, 0.4);
}

button.destructive-action {
  background-color: rgba(${destructive_rgb}, 0.5);
  color: ${fg_colour};
  border-color: rgba(${destructive_rgb}, 0.7);
  font-weight: 600;
}

button.destructive-action:hover {
  background-color: rgba(${destructive_rgb}, 0.65);
  box-shadow: 0 0 8px rgba(${destructive_rgb}, 0.4);
}

button.pill {
  border-radius: 999px;
  padding: 8px 24px;
}

button.circular {
  border-radius: 50%;
  min-width: 36px;
  min-height: 36px;
  padding: 0;
}

button.osd {
  background: rgba(${bg_window_rgb}, 0.7);
  border: 1px solid rgba(${border_rgb}, 0.5);
}

.linked > button {
  border-radius: 0;
}

.linked > button:first-child {
  border-radius: 8px 0 0 8px;
}

.linked > button:last-child {
  border-radius: 0 8px 8px 0;
}

.linked > button:only-child {
  border-radius: 8px;
}

/* ─── Text Entry ──────────────────────────────────────────────────── */
entry,
.entry {
  background-color: rgba(${bg_deep_rgb}, 0.7);
  color: ${fg_colour};
  border: 1px solid rgba(${border_rgb}, 0.5);
  border-radius: 6px;
  padding: 8px 12px;
}

entry:focus,
.entry:focus {
  border-color: rgba(${border_rgb}, 0.9);
  box-shadow: inset 0 0 6px rgba(${fg_rgb}, 0.15), 0 0 8px rgba(${glow_rgb}, 0.3);
}

entry.search,
searchentry {
  border-radius: 18px;
  padding: 6px 16px;
}

searchbar {
  background: rgba(${bg_surface_rgb}, 0.8);
  border-bottom: 1px solid rgba(${border_rgb}, 0.3);
  padding: 4px;
}

/* ─── Labels & Typography ─────────────────────────────────────────── */
label {
  color: ${fg_colour};
}

label.dim-label {
  opacity: 0.55;
}

label.error {
  color: ${error_colour};
}

label.success {
  color: ${success_colour};
}

.title,
.title-1, .title-2, .title-3, .title-4 {
  color: ${accent_bright};
  font-weight: 600;
}

/* ─── Cards & Frames ─────────────────────────────────────────────── */
.card,
.frame {
  background-color: rgba(${bg_surface_rgb}, 0.75);
  border: 1px solid rgba(${border_rgb}, 0.3);
  border-radius: 8px;
}

/* ─── Popovers ────────────────────────────────────────────────────── */
popover,
popover.background {
  background-color: rgba(${bg_window_rgb}, 0.85);
  border: 1px solid rgba(${border_rgb}, 0.4);
  border-radius: 8px;
  backdrop-filter: blur(8px);
}

/* ─── Menus ───────────────────────────────────────────────────────── */
menu {
  background-color: rgba(${bg_window_rgb}, 0.9);
  border: 1px solid rgba(${border_rgb}, 0.4);
  border-radius: 8px;
  padding: 4px;
}

menu menuitem,
modelbutton {
  color: ${fg_colour};
  border-radius: 6px;
  padding: 6px 12px;
  transition: all 0.1s ease;
}

menuitem:hover,
modelbutton:hover {
  background-color: rgba(${glow_rgb}, 0.2);
  color: ${accent_bright};
}

menu separator {
  background-color: rgba(${border_rgb}, 0.3);
  margin: 4px 8px;
  min-height: 1px;
}

/* ─── Switch ──────────────────────────────────────────────────────── */
switch {
  background-color: rgba(${bg_deep_rgb}, 0.5);
  border: 1px solid rgba(${border_rgb}, 0.4);
  border-radius: 14px;
  min-width: 40px;
  min-height: 22px;
  transition: all 0.2s ease;
}

switch slider {
  background-color: rgba(${fg_rgb}, 0.7);
  border-radius: 50%;
  min-width: 18px;
  min-height: 18px;
  margin: 2px;
  transition: all 0.2s ease;
}

switch:checked {
  background-color: rgba(${accent_bright_rgb}, 0.6);
  border-color: rgba(${accent_bright_rgb}, 0.8);
}

switch:checked slider {
  background-color: ${fg_colour};
}

/* ─── Scale / Slider ──────────────────────────────────────────────── */
scale trough {
  background-color: rgba(${bg_deep_rgb}, 0.5);
  border-radius: 4px;
  min-height: 6px;
}

scale highlight {
  background-color: rgba(${accent_bright_rgb}, 0.7);
  border-radius: 4px;
  min-height: 6px;
}

scale slider {
  background-color: ${fg_colour};
  border: 1px solid rgba(${border_rgb}, 0.5);
  border-radius: 50%;
  min-width: 18px;
  min-height: 18px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
}

scale slider:hover {
  box-shadow: 0 0 6px rgba(${glow_rgb}, 0.4);
}

scale marks mark {
  color: rgba(${fg_rgb}, 0.5);
}

scale indicator {
  background-color: rgba(${fg_rgb}, 0.3);
  min-width: 1px;
  min-height: 6px;
}

/* ─── Progress Bar ────────────────────────────────────────────────── */
progressbar trough {
  background-color: rgba(${bg_deep_rgb}, 0.5);
  border-radius: 4px;
  min-height: 6px;
}

progressbar progress {
  background-color: rgba(${accent_bright_rgb}, 0.7);
  border-radius: 4px;
  min-height: 6px;
}

/* ─── Check & Radio Buttons ───────────────────────────────────────── */
checkbutton check,
radiobutton radio {
  background-color: rgba(${bg_deep_rgb}, 0.5);
  border: 2px solid rgba(${border_rgb}, 0.5);
  min-width: 18px;
  min-height: 18px;
  transition: all 0.15s ease;
}

checkbutton check {
  border-radius: 4px;
}

radiobutton radio {
  border-radius: 50%;
}

checkbutton check:checked,
radiobutton radio:checked {
  background-color: rgba(${accent_bright_rgb}, 0.6);
  border-color: rgba(${accent_bright_rgb}, 0.8);
  color: ${fg_colour};
}

checkbutton check:hover,
radiobutton radio:hover {
  border-color: rgba(${border_rgb}, 0.8);
  box-shadow: 0 0 4px rgba(${glow_rgb}, 0.3);
}

/* ─── Sidebar & Navigation ────────────────────────────────────────── */
.sidebar,
.navigation-sidebar,
placessidebar {
  background-color: rgba(${bg_deep_rgb}, 0.6);
  border-right: 1px solid rgba(${border_rgb}, 0.2);
  color: ${fg_colour};
}

.sidebar row,
.sidebar-row,
placessidebar row {
  border-radius: 6px;
  padding: 4px 8px;
  transition: all 0.1s ease;
}

.sidebar row:hover,
placessidebar row:hover {
  background: rgba(${accent_rgb}, 0.15);
}

.sidebar row:selected,
placessidebar row:selected {
  background: rgba(${accent_bright_rgb}, 0.3);
  color: ${accent_bright};
  font-weight: 600;
}

/* ─── Scrollbar ───────────────────────────────────────────────────── */
scrollbar {
  background-color: rgba(${bg_deep_rgb}, 0.5);
}

scrollbar > trough {
  background-color: rgba(${bg_window_rgb}, 0.6);
  border-radius: 4px;
}

scrollbar > trough > slider {
  background-color: rgba(${border_rgb}, 0.6);
  border-radius: 4px;
  min-width: 6px;
  min-height: 6px;
}

scrollbar > trough > slider:hover {
  background-color: rgba(${glow_rgb}, 0.85);
}

/* ─── Tabs / Notebook / Stack ─────────────────────────────────────── */
notebook header {
  background: rgba(${bg_surface_rgb}, 0.7);
  border-bottom: 1px solid rgba(${border_rgb}, 0.3);
}

notebook tab,
.tab {
  background-color: rgba(${bg_surface_rgb}, 0.7);
  color: rgba(${fg_rgb}, 0.7);
  border-radius: 6px 6px 0 0;
  margin-right: 2px;
  padding: 8px 16px;
}

notebook tab:checked,
.tab:checked {
  background-color: rgba(${accent_rgb}, 0.35);
  color: ${accent_bright};
  border-bottom: 3px solid rgba(${border_rgb}, 0.9);
  box-shadow: 0 0 8px rgba(${glow_rgb}, 0.3);
}

stackswitcher button {
  border-radius: 0;
}

stackswitcher button:checked {
  background: rgba(${accent_rgb}, 0.3);
  border-bottom: 2px solid ${accent_bright};
}

tabbar tab {
  background: rgba(${bg_surface_rgb}, 0.6);
  border-radius: 8px 8px 0 0;
  padding: 4px 12px;
}

tabbar tab:checked {
  background: rgba(${accent_rgb}, 0.25);
}

/* ─── Toast & Infobar ─────────────────────────────────────────────── */
toast {
  background: rgba(${bg_window_rgb}, 0.9);
  border: 1px solid rgba(${border_rgb}, 0.5);
  border-radius: 8px;
  color: ${fg_colour};
  padding: 8px 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
}

toast button {
  background: transparent;
  color: ${accent_bright};
  font-weight: 600;
}

infobar {
  border: 1px solid rgba(${border_rgb}, 0.4);
  border-radius: 6px;
  padding: 8px 12px;
}

infobar.info {
  background: rgba(${info_rgb}, 0.2);
  border-color: rgba(${info_rgb}, 0.4);
}

infobar.warning {
  background: rgba(${warning_rgb}, 0.2);
  border-color: rgba(${warning_rgb}, 0.4);
}

infobar.error {
  background: rgba(${error_rgb}, 0.2);
  border-color: rgba(${error_rgb}, 0.4);
}

infobar.question {
  background: rgba(${accent_rgb}, 0.2);
  border-color: rgba(${accent_rgb}, 0.4);
}

/* ─── Dialogs ─────────────────────────────────────────────────────── */
dialog,
messagedialog {
  background: rgba(${bg_window_rgb}, 0.92);
  border-radius: ${radius}px;
}

.dialog-action-area button {
  border-radius: 0;
  border: none;
  border-top: 1px solid rgba(${border_rgb}, 0.2);
}

filechooser {
  background: rgba(${bg_window_rgb}, 0.92);
}

filechooser pathbar button {
  border-radius: 4px;
}

aboutdialog .main-page {
  background: rgba(${bg_surface_rgb}, 0.85);
}

/* ─── Searchbar ───────────────────────────────────────────────────── */
searchbar {
  background: rgba(${bg_surface_rgb}, 0.8);
  border-bottom: 1px solid rgba(${border_rgb}, 0.3);
}

/* ─── Separator ───────────────────────────────────────────────────── */
separator {
  background-color: rgba(${border_rgb}, 0.3);
  min-width: 1px;
  min-height: 1px;
}

/* ─── Calendar Widget ─────────────────────────────────────────────── */
calendar {
  background: rgba(${bg_surface_rgb}, 0.8);
  border: 1px solid rgba(${border_rgb}, 0.3);
  border-radius: 8px;
  padding: 4px;
}

calendar header {
  color: ${accent_bright};
  font-weight: 600;
}

calendar.day {
  border-radius: 50%;
  transition: all 0.1s ease;
}

calendar.day:hover {
  background: rgba(${accent_rgb}, 0.2);
}

calendar.today {
  background: rgba(${accent_bright_rgb}, 0.3);
  border: 1px solid rgba(${border_rgb}, 0.6);
  font-weight: bold;
  color: ${accent_bright};
}

/* ─── Text View ───────────────────────────────────────────────────── */
textview,
textview text {
  background-color: rgba(${bg_deep_rgb}, 0.7);
  color: ${fg_colour};
}

/* ─── Tooltips ────────────────────────────────────────────────────── */
tooltip,
tooltip.background {
  background-color: rgba(${bg_window_rgb}, 0.9);
  border: 1px solid rgba(${border_rgb}, 0.5);
  border-radius: 6px;
  color: ${fg_colour};
  padding: 4px 8px;
}

/* ─── Spinner ─────────────────────────────────────────────────────── */
spinner {
  color: ${accent_bright};
}

/* ─── Level Bar ───────────────────────────────────────────────────── */
levelbar trough {
  background-color: rgba(${bg_deep_rgb}, 0.5);
  border-radius: 4px;
  min-height: 6px;
}

levelbar block {
  border-radius: 4px;
  min-height: 6px;
}

levelbar block.filled {
  background-color: rgba(${accent_bright_rgb}, 0.7);
}

levelbar block.empty {
  background-color: rgba(${bg_deep_rgb}, 0.3);
}

/* ─── Link Button ─────────────────────────────────────────────────── */
linkbutton {
  color: ${accent_bright};
}

linkbutton:visited {
  color: ${accent_colour};
}

/* ─── Paned ───────────────────────────────────────────────────────── */
paned > separator {
  background-color: rgba(${border_rgb}, 0.3);
  min-width: 4px;
  min-height: 4px;
}

paned > separator:hover {
  background-color: rgba(${accent_rgb}, 0.4);
}

/* ─── Selection Mode ──────────────────────────────────────────────── */
.selection-mode headerbar {
  background: linear-gradient(180deg, rgba(${accent_rgb}, 0.4), rgba(${accent_rgb}, 0.3));
  border-color: rgba(${accent_bright_rgb}, 0.5);
}

/* ─── OSD Overlay ─────────────────────────────────────────────────── */
.osd,
.osd toolbar {
  background: rgba(${bg_window_rgb}, 0.75);
  border-radius: ${radius}px;
  backdrop-filter: blur(8px);
}

overlay {
  background: transparent;
}

/* ─── Spin Button ─────────────────────────────────────────────────── */
spinbutton {
  background-color: rgba(${bg_deep_rgb}, 0.7);
  border: 1px solid rgba(${border_rgb}, 0.5);
  border-radius: 6px;
}

spinbutton button {
  background: rgba(${accent_rgb}, 0.2);
  border: none;
  border-radius: 0;
}

spinbutton entry {
  border: none;
  background: transparent;
}

/* ─── Dropdown / Combobox ─────────────────────────────────────────── */
dropdown,
combobox {
  background: rgba(${bg_deep_rgb}, 0.7);
  border: 1px solid rgba(${border_rgb}, 0.5);
  border-radius: 6px;
}

dropdown button {
  background: transparent;
}

dropdown popover {
  background: rgba(${bg_window_rgb}, 0.9);
  border-radius: 8px;
}

/* ─── Flow Box ────────────────────────────────────────────────────── */
flowboxchild {
  border-radius: 6px;
  padding: 4px;
  transition: all 0.1s ease;
}

flowboxchild:selected {
  background: rgba(${accent_bright_rgb}, 0.3);
}

/* ─── Status Page (Libadwaita) ────────────────────────────────────── */
statuspage {
  background: transparent;
}

statuspage .icon {
  color: rgba(${fg_rgb}, 0.4);
}

/* ─── Libadwaita Widgets ──────────────────────────────────────────── */
.boxed-list {
  background: rgba(${bg_surface_rgb}, 0.7);
  border: 1px solid rgba(${border_rgb}, 0.3);
  border-radius: ${radius}px;
}

.boxed-list row {
  border-bottom: 1px solid rgba(${border_rgb}, 0.15);
  padding: 8px 12px;
}

.boxed-list row:last-child {
  border-bottom: none;
}

preferencespage {
  background: transparent;
}

preferencesgroup {
  margin: 12px;
}

actionrow,
preferencesrow {
  padding: 8px 12px;
  transition: all 0.1s ease;
}

actionrow:hover,
preferencesrow:hover {
  background: rgba(${accent_rgb}, 0.08);
}

switchrow switch {
  margin: 4px 0;
}

entryrow entry {
  background: transparent;
  border: none;
}

comborow dropdown {
  background: transparent;
  border: none;
}

.property {
  color: rgba(${fg_rgb}, 0.7);
}

banner {
  background: rgba(${accent_rgb}, 0.15);
  border-bottom: 1px solid rgba(${accent_rgb}, 0.3);
  padding: 8px 16px;
}

window.about .main-page {
  background: rgba(${bg_surface_rgb}, 0.85);
}

toolbarview {
  background: transparent;
}

/* ─── Accent & Disabled ───────────────────────────────────────────── */
.accent {
  color: ${accent_bright};
}

:disabled {
  opacity: 0.45;
  color: rgba(${fg_rgb}, 0.5);
}
CSSEOF
)"

    write_target_file "$outfile" "$css"

    # ── Install to user GTK config ───────────────────────────────────────
    if [[ "$DRY_RUN" != true ]]; then
        local gtk4_dest="${HOME}/.config/gtk-4.0"
        local gtk3_dest="${HOME}/.config/gtk-3.0"
        mkdir -p "$gtk4_dest"
        cp "$outfile" "${gtk4_dest}/gtk.css"
        log_success "Installed: ${gtk4_dest}/gtk.css"
        if [[ ! -e "$gtk3_dest" ]]; then
            ln -s gtk-4.0 "${HOME}/.config/gtk-3.0"
            log_verbose "Symlinked ~/.config/gtk-3.0 → gtk-4.0"
        fi
    fi
}
