#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# icons.sh — Icon colour tinting scaffold for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates an index.theme and a colour-mapping file for recolouring icon sets
# (e.g. Papirus, Yaru) with palette-derived accent colours.
#
# This is a scaffold — actual SVG recolouring requires post-processing with
# sed/xslt on the source icon SVGs.
# ═══════════════════════════════════════════════════════════════════════════════

generate_icons() {
    local outdir="${OUTPUT_DIR}/${THEME_NAME}/icons"
    local index_file="${outdir}/index.theme"
    local colours_file="${outdir}/colour-map.sh"

    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local accent folder_colour symbol_colour
    accent="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"
    folder_colour="${PRIMARY_SHADES[5]:-$primary_hex}"
    symbol_colour="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"

    local folder_dark folder_light
    folder_dark="$(darken "$folder_colour" 0.15)"
    folder_light="$(lighten "$folder_colour" 0.15)"

    local index_content
    index_content="$(cat << IDXEOF
[Icon Theme]
Name=${THEME_NAME}
Comment=Palette-tinted icon theme — generated by uiGen (https://github.com/XAOSTECH/design-flows), colours derived with pastel (https://github.com/sharkdp/pastel)
Inherits=Papirus,hicolor
Example=folder

Directories=16x16/places,22x22/places,24x24/places,32x32/places,48x48/places,64x64/places

[16x16/places]
Size=16
Type=Fixed

[22x22/places]
Size=22
Type=Fixed

[24x24/places]
Size=24
Type=Fixed

[32x32/places]
Size=32
Type=Fixed

[48x48/places]
Size=48
Type=Fixed

[64x64/places]
Size=64
Type=Fixed
IDXEOF
)"

    local map_content
    map_content="$(cat << MAPEOF
#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# ${THEME_NAME} — Icon colour mapping
# Generated by uiGen (https://github.com/XAOSTECH/design-flows)
# Colours derived with pastel (https://github.com/sharkdp/pastel)
#
# Usage: source this file then call tint_icons <source_dir> <dest_dir>
# Requires: sed, find
# ═══════════════════════════════════════════════════════════════════

ICON_ACCENT="${accent}"
ICON_FOLDER="${folder_colour}"
ICON_FOLDER_DARK="${folder_dark}"
ICON_FOLDER_LIGHT="${folder_light}"
ICON_SYMBOL="${symbol_colour}"

# Papirus default folder colours to replace
declare -A ICON_COLOUR_MAP=(
    ["#5294e2"]="${folder_colour}"
    ["#4877b1"]="${folder_dark}"
    ["#6eb2e5"]="${folder_light}"
)

tint_icons() {
    local src="\$1" dest="\$2"
    if [[ -z "\$src" ]] || [[ -z "\$dest" ]]; then
        echo "Usage: tint_icons <source_icon_dir> <dest_icon_dir>"
        return 1
    fi
    cp -r "\$src" "\$dest"
    for old_colour in "\${!ICON_COLOUR_MAP[@]}"; do
        local new_colour="\${ICON_COLOUR_MAP[\$old_colour]}"
        find "\$dest" -name '*.svg' -exec sed -i "s/\${old_colour}/\${new_colour}/gi" {} +
    done
    echo "Tinted icons written to \$dest"
}
MAPEOF
)"

    write_target_file "$index_file" "$index_content"
    write_target_file "$colours_file" "$map_content"
}
