#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# kde.sh — KDE Plasma colour scheme target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates a .colors file compatible with KDE Plasma's colour scheme format.
# Can be installed to ~/.local/share/color-schemes/
# ═══════════════════════════════════════════════════════════════════════════════

_hex_to_kde_rgb() {
    local hex="${1#\#}"
    printf "%d,%d,%d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

generate_kde() {
    local outfile="${OUTPUT_DIR}/${THEME_NAME}/kde/${THEME_NAME}.colors"

    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg accent bg bg_alt
    fg="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    accent="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"
    bg="$(set_lightness "$tertiary_hex" "$BG_LIGHTNESS")"
    bg_alt="$(lighten "$bg" 0.05)"

    local border inactive link visited
    border="${PRIMARY_SHADES[6]:-$(lighten "$primary_hex" 0.25)}"
    inactive="$(desaturate "$fg" 0.3)"
    link="$accent"
    visited="$(desaturate "$accent" 0.2)"

    local hover_bg focus_bg negative positive neutral
    hover_bg="$(lighten "$bg" 0.1)"
    focus_bg="$(lighten "$bg" 0.15)"
    negative="${COMPLEMENTARY_COLOURS[0]:-$(rotate_hue "$primary_hex" 180)}"
    positive="${TRIADIC_COLOURS[2]:-$(rotate_hue "$primary_hex" 120)}"
    neutral="${ANALOGOUS_COLOURS[2]:-$(rotate_hue "$secondary_hex" 30)}"

    local fg_kde accent_kde bg_kde bg_alt_kde border_kde inactive_kde
    fg_kde=$(_hex_to_kde_rgb "$fg")
    accent_kde=$(_hex_to_kde_rgb "$accent")
    bg_kde=$(_hex_to_kde_rgb "$bg")
    bg_alt_kde=$(_hex_to_kde_rgb "$bg_alt")
    border_kde=$(_hex_to_kde_rgb "$border")
    inactive_kde=$(_hex_to_kde_rgb "$inactive")

    local link_kde visited_kde hover_kde focus_kde
    link_kde=$(_hex_to_kde_rgb "$link")
    visited_kde=$(_hex_to_kde_rgb "$visited")
    hover_kde=$(_hex_to_kde_rgb "$hover_bg")
    focus_kde=$(_hex_to_kde_rgb "$focus_bg")

    local neg_kde pos_kde neut_kde
    neg_kde=$(_hex_to_kde_rgb "$negative")
    pos_kde=$(_hex_to_kde_rgb "$positive")
    neut_kde=$(_hex_to_kde_rgb "$neutral")

    local content
    content="$(cat << KDEEOF
# ${THEME_NAME} — KDE Plasma Colour Scheme
# Generated by uiGen (https://github.com/XAOSTECH/design-flows)
# Colours derived with pastel (https://github.com/sharkdp/pastel)

[General]
Name=${THEME_NAME}
ColorScheme=${THEME_NAME}
shadeSortColumn=true

[Colors:Window]
ForegroundNormal=${fg_kde}
ForegroundInactive=${inactive_kde}
ForegroundActive=${accent_kde}
ForegroundLink=${link_kde}
ForegroundVisited=${visited_kde}
ForegroundNegative=${neg_kde}
ForegroundPositive=${pos_kde}
ForegroundNeutral=${neut_kde}
BackgroundNormal=${bg_kde}
BackgroundAlternate=${bg_alt_kde}
DecorationFocus=${accent_kde}
DecorationHover=${hover_kde}

[Colors:View]
ForegroundNormal=${fg_kde}
ForegroundInactive=${inactive_kde}
ForegroundActive=${accent_kde}
ForegroundLink=${link_kde}
ForegroundVisited=${visited_kde}
ForegroundNegative=${neg_kde}
ForegroundPositive=${pos_kde}
ForegroundNeutral=${neut_kde}
BackgroundNormal=${bg_kde}
BackgroundAlternate=${bg_alt_kde}
DecorationFocus=${accent_kde}
DecorationHover=${hover_kde}

[Colors:Button]
ForegroundNormal=${fg_kde}
ForegroundInactive=${inactive_kde}
ForegroundActive=${accent_kde}
ForegroundLink=${link_kde}
ForegroundVisited=${visited_kde}
ForegroundNegative=${neg_kde}
ForegroundPositive=${pos_kde}
ForegroundNeutral=${neut_kde}
BackgroundNormal=${bg_alt_kde}
BackgroundAlternate=${bg_kde}
DecorationFocus=${accent_kde}
DecorationHover=${hover_kde}

[Colors:Selection]
ForegroundNormal=${bg_kde}
ForegroundInactive=${bg_alt_kde}
ForegroundActive=${bg_kde}
ForegroundLink=${bg_kde}
ForegroundVisited=${bg_kde}
ForegroundNegative=${bg_kde}
ForegroundPositive=${bg_kde}
ForegroundNeutral=${bg_kde}
BackgroundNormal=${accent_kde}
BackgroundAlternate=${focus_kde}
DecorationFocus=${accent_kde}
DecorationHover=${hover_kde}

[Colors:Tooltip]
ForegroundNormal=${fg_kde}
ForegroundInactive=${inactive_kde}
ForegroundActive=${accent_kde}
ForegroundLink=${link_kde}
ForegroundVisited=${visited_kde}
ForegroundNegative=${neg_kde}
ForegroundPositive=${pos_kde}
ForegroundNeutral=${neut_kde}
BackgroundNormal=${bg_kde}
BackgroundAlternate=${bg_alt_kde}
DecorationFocus=${accent_kde}
DecorationHover=${hover_kde}

[Colors:Complementary]
ForegroundNormal=${fg_kde}
ForegroundInactive=${inactive_kde}
ForegroundActive=${accent_kde}
ForegroundLink=${link_kde}
ForegroundVisited=${visited_kde}
ForegroundNegative=${neg_kde}
ForegroundPositive=${pos_kde}
ForegroundNeutral=${neut_kde}
BackgroundNormal=${bg_kde}
BackgroundAlternate=${bg_alt_kde}
DecorationFocus=${accent_kde}
DecorationHover=${hover_kde}

[Colors:Header]
ForegroundNormal=${fg_kde}
ForegroundInactive=${inactive_kde}
ForegroundActive=${accent_kde}
ForegroundLink=${link_kde}
ForegroundVisited=${visited_kde}
ForegroundNegative=${neg_kde}
ForegroundPositive=${pos_kde}
ForegroundNeutral=${neut_kde}
BackgroundNormal=${bg_alt_kde}
BackgroundAlternate=${bg_kde}
DecorationFocus=${accent_kde}
DecorationHover=${hover_kde}

[WM]
activeBackground=${bg_alt_kde}
activeForeground=${fg_kde}
inactiveBackground=${bg_kde}
inactiveForeground=${inactive_kde}
activeBlend=${accent_kde}
inactiveBlend=${bg_kde}
activeTitleBtnBg=${bg_alt_kde}
inactiveTitleBtnBg=${bg_kde}
KDEEOF
)"

    write_target_file "$outfile" "$content"
}
