#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# rofi.sh — Rofi / Wofi launcher theme target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates a .rasi colour theme for Rofi (also usable by Wofi with minor
# adjustments). Covers: window, inputbar, listview, element, sidebar, message.
# ═══════════════════════════════════════════════════════════════════════════════

generate_rofi() {
    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg bg accent bg_alt border urgent
    fg="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    bg="$(set_lightness "$tertiary_hex" "$BG_LIGHTNESS")"
    accent="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"
    bg_alt="$(lighten "$bg" 0.05)"
    border="${PRIMARY_SHADES[6]:-$(lighten "$primary_hex" 0.25)}"
    urgent="${COMPLEMENTARY_COLOURS[0]:-$(rotate_hue "$primary_hex" 180)}"

    local fg_rgb bg_rgb accent_rgb bg_alt_rgb border_rgb urgent_rgb
    fg_rgb="$(hex_to_rgb "$fg")"
    bg_rgb="$(hex_to_rgb "$bg")"
    accent_rgb="$(hex_to_rgb "$accent")"
    bg_alt_rgb="$(hex_to_rgb "$bg_alt")"
    border_rgb="$(hex_to_rgb "$border")"
    urgent_rgb="$(hex_to_rgb "$urgent")"

    local rasi
    rasi="$(cat << RASIEOF
/* ═══════════════════════════════════════════════════════════════════
 * ${THEME_NAME} — Rofi colour theme
 * Generated by uiGen (https://github.com/XAOSTECH/design-flows)
 * Colours derived with pastel (https://github.com/sharkdp/pastel)
 *
 * Usage:  rofi -theme ${THEME_NAME}
 * Or:     @import "${THEME_NAME}"  in your main .rasi config
 * ═══════════════════════════════════════════════════════════════════ */

* {
    font:           "Inter 12";

    bg:             rgba(${bg_rgb}, 1.0);
    bg-alt:         rgba(${bg_alt_rgb}, 1.0);
    fg:             rgba(${fg_rgb}, 1.0);
    fg-dim:         rgba(${fg_rgb}, 0.55);
    accent:         rgba(${accent_rgb}, 1.0);
    border-colour:  rgba(${border_rgb}, 0.6);
    urgent:         rgba(${urgent_rgb}, 1.0);
    transparent:    rgba(0, 0, 0, 0.0);

    background-color: @transparent;
    text-color:       @fg;
}

window {
    width:            38%;
    border:           2px;
    border-color:     @border-colour;
    border-radius:    ${BORDER_RADIUS:-12}px;
    background-color: @bg;
    padding:          0;
}

mainbox {
    children: [ inputbar, message, listview ];
    spacing:  0;
    padding:  0;
}

inputbar {
    padding:          12px 16px;
    spacing:          8px;
    background-color: @bg-alt;
    children:         [ prompt, entry ];
}

prompt {
    text-color: @accent;
}

entry {
    placeholder:       "Search\u2026";
    placeholder-color: @fg-dim;
}

message {
    padding:          8px 16px;
    background-color: @bg-alt;
    border:           0 0 1px 0;
    border-color:     @border-colour;
}

textbox {
    text-color: @fg-dim;
}

listview {
    lines:    12;
    columns:  1;
    padding:  4px 0;
    scrollbar: false;
    fixed-height: true;
}

element {
    padding:  8px 16px;
    spacing:  8px;
}

element.normal.normal {
    background-color: @transparent;
    text-color:       @fg;
}

element.normal.urgent {
    text-color: @urgent;
}

element.normal.active {
    text-color: @accent;
}

element.selected.normal {
    background-color: @accent;
    text-color:       @bg;
    border-radius:    4px;
}

element.selected.urgent {
    background-color: @urgent;
    text-color:       @bg;
}

element.selected.active {
    background-color: @accent;
    text-color:       @bg;
}

element.alternate.normal {
    background-color: @transparent;
    text-color:       @fg;
}

element-icon {
    size: 1.2em;
}

element-text {
    vertical-align: 0.5;
}

sidebar {
    padding:          4px 0;
    background-color: @bg-alt;
    border:           1px 0 0 0;
    border-color:     @border-colour;
}

button {
    padding:    8px;
    text-color: @fg-dim;
}

button.selected {
    text-color: @accent;
    font:       "Inter Bold 12";
}
RASIEOF
)"

    write_target_file "${OUTPUT_DIR}/${THEME_NAME}/rofi/${THEME_NAME}.rasi" "$rasi"

    # ── Install to user rofi themes ──────────────────────────────────────
    if [[ "$DRY_RUN" != true ]]; then
        local dest="${HOME}/.local/share/rofi/themes"
        mkdir -p "$dest"
        cp "${OUTPUT_DIR}/${THEME_NAME}/rofi/${THEME_NAME}.rasi" "${dest}/${THEME_NAME}.rasi"
        log_success "Installed: ${dest}/${THEME_NAME}.rasi"
        log_info "Use with: rofi -theme '${THEME_NAME}'"
    fi
}
