#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# terminals.sh — Terminal emulator theme target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates colour configs for kitty, alacritty, and foot from the palette.
# Maps the 16 ANSI colours from palette shades/analogous/triadic arrays.
# ═══════════════════════════════════════════════════════════════════════════════

generate_terminals() {
    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg bg cursor selection
    fg="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    bg="$(set_lightness "$tertiary_hex" "$BG_LIGHTNESS")"
    cursor="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"
    selection="${PRIMARY_SHADES[5]:-$primary_hex}"

    # ANSI 16 colours mapped from palette
    local color0 color1 color2 color3 color4 color5 color6 color7
    local color8 color9 color10 color11 color12 color13 color14 color15

    color0="$(darken "$bg" 0.05)"                                          # black
    color1="${COMPLEMENTARY_COLOURS[0]:-$(rotate_hue "$primary_hex" 180)}"  # red
    color2="${TRIADIC_COLOURS[2]:-$(rotate_hue "$primary_hex" 120)}"        # green
    color3="${ANALOGOUS_COLOURS[2]:-$(rotate_hue "$secondary_hex" 30)}"     # yellow
    color4="${ANALOGOUS_COLOURS[0]:-$(rotate_hue "$primary_hex" 30)}"       # blue
    color5="$primary_hex"                                                   # magenta
    color6="${TRIADIC_COLOURS[0]:-$(rotate_hue "$primary_hex" 120)}"        # cyan
    color7="$(lighten "$fg" 0.0)"                                           # white

    color8="$(lighten "$color0" 0.15)"    # bright black
    color9="$(lighten "$color1" 0.1)"     # bright red
    color10="$(lighten "$color2" 0.1)"    # bright green
    color11="$(lighten "$color3" 0.1)"    # bright yellow
    color12="$(lighten "$color4" 0.1)"    # bright blue
    color13="$(lighten "$color5" 0.1)"    # bright magenta
    color14="$(lighten "$color6" 0.1)"    # bright cyan
    color15="$(lighten "$color7" 0.1)"    # bright white

    # ── kitty ────────────────────────────────────────────────────────────────
    local kitty_conf
    kitty_conf="$(cat << KITTYEOF
# ${THEME_NAME} — kitty colour theme
# Generated by uiGen (https://github.com/XAOSTECH/design-flows)
# Colours derived with pastel (https://github.com/sharkdp/pastel)
#
# Place in ~/.config/kitty/ and add: include ${THEME_NAME}.conf

foreground ${fg}
background ${bg}
cursor     ${cursor}
selection_foreground ${bg}
selection_background ${selection}

color0  ${color0}
color1  ${color1}
color2  ${color2}
color3  ${color3}
color4  ${color4}
color5  ${color5}
color6  ${color6}
color7  ${color7}
color8  ${color8}
color9  ${color9}
color10 ${color10}
color11 ${color11}
color12 ${color12}
color13 ${color13}
color14 ${color14}
color15 ${color15}
KITTYEOF
)"

    # ── Alacritty ────────────────────────────────────────────────────────────
    local alacritty_toml
    alacritty_toml="$(cat << ALAEOF
# ${THEME_NAME} — Alacritty colour theme
# Generated by uiGen (https://github.com/XAOSTECH/design-flows)
# Colours derived with pastel (https://github.com/sharkdp/pastel)
#
# Place in ~/.config/alacritty/ and import in alacritty.toml

[colors.primary]
foreground = "${fg}"
background = "${bg}"

[colors.cursor]
text   = "${bg}"
cursor = "${cursor}"

[colors.selection]
text       = "${bg}"
background = "${selection}"

[colors.normal]
black   = "${color0}"
red     = "${color1}"
green   = "${color2}"
yellow  = "${color3}"
blue    = "${color4}"
magenta = "${color5}"
cyan    = "${color6}"
white   = "${color7}"

[colors.bright]
black   = "${color8}"
red     = "${color9}"
green   = "${color10}"
yellow  = "${color11}"
blue    = "${color12}"
magenta = "${color13}"
cyan    = "${color14}"
white   = "${color15}"
ALAEOF
)"

    # ── foot ─────────────────────────────────────────────────────────────────
    local foot_ini
    foot_ini="$(cat << FOOTEOF
# ${THEME_NAME} — foot colour theme
# Generated by uiGen (https://github.com/XAOSTECH/design-flows)
# Colours derived with pastel (https://github.com/sharkdp/pastel)
#
# Place in ~/.config/foot/ and add: include=${THEME_NAME}.ini

[colors]
foreground = ${fg#\#}
background = ${bg#\#}

[cursor]
color = ${bg#\#} ${cursor#\#}

[colors]
selection-foreground = ${bg#\#}
selection-background = ${selection#\#}

regular0 = ${color0#\#}
regular1 = ${color1#\#}
regular2 = ${color2#\#}
regular3 = ${color3#\#}
regular4 = ${color4#\#}
regular5 = ${color5#\#}
regular6 = ${color6#\#}
regular7 = ${color7#\#}

bright0 = ${color8#\#}
bright1 = ${color9#\#}
bright2 = ${color10#\#}
bright3 = ${color11#\#}
bright4 = ${color12#\#}
bright5 = ${color13#\#}
bright6 = ${color14#\#}
bright7 = ${color15#\#}
FOOTEOF
)"

    local base="${OUTPUT_DIR}/${THEME_NAME}/terminals"
    write_target_file "${base}/kitty/${THEME_NAME}.conf" "$kitty_conf"
    write_target_file "${base}/alacritty/${THEME_NAME}.toml" "$alacritty_toml"
    write_target_file "${base}/foot/${THEME_NAME}.ini" "$foot_ini"

    # ── Install to user config directories ───────────────────────────────
    if [[ "$DRY_RUN" != true ]]; then
        local kitty_dest="${HOME}/.config/kitty"
        if [[ -d "$kitty_dest" ]]; then
            cp "${base}/kitty/${THEME_NAME}.conf" "${kitty_dest}/"
            log_success "Installed: ${kitty_dest}/${THEME_NAME}.conf"
        fi

        local ala_dest="${HOME}/.config/alacritty"
        if [[ -d "$ala_dest" ]]; then
            cp "${base}/alacritty/${THEME_NAME}.toml" "${ala_dest}/"
            log_success "Installed: ${ala_dest}/${THEME_NAME}.toml"
        fi

        local foot_dest="${HOME}/.config/foot"
        if [[ -d "$foot_dest" ]]; then
            cp "${base}/foot/${THEME_NAME}.ini" "${foot_dest}/"
            log_success "Installed: ${foot_dest}/${THEME_NAME}.ini"
        fi
    fi
}
