#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# tmux.sh — tmux colour theme target for uiGen
# ═══════════════════════════════════════════════════════════════════════════════
# Generates a .tmux.conf snippet with status bar, pane border, message, and
# mode colours derived from the palette.
# ═══════════════════════════════════════════════════════════════════════════════

generate_tmux() {
    local outfile="${OUTPUT_DIR}/${THEME_NAME}/tmux/${THEME_NAME}.tmux.conf"

    local primary_hex secondary_hex tertiary_hex
    primary_hex=$(get_hex "$PRIMARY_COLOUR")
    secondary_hex=$(get_hex "$SECONDARY_COLOUR")
    tertiary_hex=$(get_hex "$TERTIARY_COLOUR")

    local fg_colour accent_colour bg_colour border_colour active_colour
    fg_colour="${PRIMARY_SHADES[8]:-$(lighten "$primary_hex" 0.35)}"
    accent_colour="${PRIMARY_SHADES[5]:-$primary_hex}"
    bg_colour="$(set_lightness "$tertiary_hex" "$BG_LIGHTNESS")"
    border_colour="${PRIMARY_SHADES[6]:-$(lighten "$primary_hex" 0.25)}"
    active_colour="${PRIMARY_SHADES[3]:-$(saturate "$primary_hex" 0.2)}"

    local inactive_colour
    inactive_colour="${BLEND_COLOURS[0]:-$(mix_colors "$primary_hex" "$secondary_hex" 0.5)}"

    local conf
    conf="$(cat << CONFEOF
# ═══════════════════════════════════════════════════════════════════
# ${THEME_NAME} — tmux colour theme
# Generated by uiGen (https://github.com/XAOSTECH/design-flows)
# Colours derived with pastel (https://github.com/sharkdp/pastel)
#
# Source this file from your .tmux.conf:
#   source-file ~/.config/tmux/${THEME_NAME}.tmux.conf
# ═══════════════════════════════════════════════════════════════════

# Status bar
set -g status-style "bg=${bg_colour},fg=${fg_colour}"
set -g status-left-style "bg=${accent_colour},fg=${bg_colour},bold"
set -g status-right-style "bg=${bg_colour},fg=${accent_colour}"

# Window tabs
set -g window-status-style "bg=${bg_colour},fg=${inactive_colour}"
set -g window-status-current-style "bg=${accent_colour},fg=${bg_colour},bold"
set -g window-status-activity-style "bg=${bg_colour},fg=${active_colour},underscore"

# Pane borders
set -g pane-border-style "fg=${border_colour}"
set -g pane-active-border-style "fg=${active_colour}"

# Messages
set -g message-style "bg=${accent_colour},fg=${bg_colour}"
set -g message-command-style "bg=${bg_colour},fg=${accent_colour}"

# Mode (copy/choice)
set -g mode-style "bg=${accent_colour},fg=${bg_colour}"

# Clock
set -g clock-mode-colour "${active_colour}"

# Bell
set -g window-status-bell-style "bg=${active_colour},fg=${bg_colour},bold"
CONFEOF
)"

    write_target_file "$outfile" "$conf"
}
